In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, transform, img_as_float

In [ ]:
x = [1, 2, 4, 5, 7]
print(x)

[1, 2, 4, 5, 7]


In [ ]:
for i in range(len(x)):
  x[i] = x[i] + 4
print(x)

[5, 6, 8, 9, 11]


In [ ]:
x = np.array([1, 2, 4, 5, 7])
print(x)

[1 2 4 5 7]


In [ ]:
x = x+4
print(x)

[ 5  6  8  9 11]


2 3 4

5 6 7

In [ ]:
# declare an array of 2 rows, 3 columns
x = np.array([[2,3,4],[5,6,7]])

In [ ]:
print(x)

[[2 3 4]
 [5 6 7]]


In [ ]:
x = np.array([1, 2, 4, 5, 7])

In [ ]:
print(x[3])

5


In [ ]:
print(x[-2])

5


In [ ]:
x = np.array([[2,3,4],[5,6,7]])
print(x[1][1])
print(x[1,1])

6
6


In [ ]:
x = np.array([[[2,3,4],[5,6,7]],[[2,3,4],[5,6,7]]])
print(x)

[[[2 3 4]
  [5 6 7]]

 [[2 3 4]
  [5 6 7]]]


x[start:end] = [x[start], x[start+1], ....., x[end-1]]

In [ ]:
x = np.array([1, 2, 4, 5, 7])
print(x[1:4])

[2 4 5]


In [ ]:
print(x[1:-1])

[2 4 5]


x[start:end:step] = x[start], x[start+step], x[start+2*step],.... x[end-1]

In [ ]:
print(x[0:5:1])

[1 2 4 5 7]


In [ ]:
print(x[1:4:2])

[2 5]


In [ ]:
print(x[::1])

[1 2 4 5 7]


In [ ]:
print(x[::-1])

[7 5 4 2 1]


In [ ]:
print(x[::-2])

[7 4 1]


In [ ]:
x = np.array([[2,3,4],[5,6,7]])
print(x)

[[2 3 4]
 [5 6 7]]


In [ ]:
print(x[0,:])

[2 3 4]


In [ ]:
print(x[:,-1:])

[[4]
 [7]]


In [ ]:
print(x[:,::2])

[[2 4]
 [5 7]]


`x[start:end]`

`x[start:end:step]`

`x[::]`

start is not specified, 0

end is not specified, len(x)

step is not specified, 1

In [ ]:
# boolean indexing

x = np.array([0, 1, -5, -4, 4, 5])


In [ ]:
index = [False, False, True, True, False, False]

In [ ]:
x[index]

array([-5, -4])

In [ ]:
index = x < 0

In [ ]:
index

array([False, False, False])

In [ ]:
x[index]

array([-5, -4])

In [ ]:
x[ x < 0 ]

array([-5, -4])

## Slicing Summary

`x[start:end:step] = [x[start], x[start+step], x[start+2*step], ... x[end-1]]`

If `start` not specified, assumes `0`

If `end` not specified, assumes `len(x)`

If `step` not specified, assumes `1`

**Boolean indexing**: `x[ind]` where `ind` is an array of `True` and `False` with the same size as `x` 

In [ ]:
x = np.array([4, 1, -1, 2, 4, 5])
print(x[1:4]) # [1, -1, 2] 
print(x[1:]) # [1, -1, 2, 4, 5]
print(x[:4]) # []
print(x[:]) # []
print(x[2::2]) # []
print(x[:6:2]) # []

[ 1 -1  2]
[ 1 -1  2  4  5]
[ 4  1 -1  2]
[ 4  1 -1  2  4  5]
[-1  4]
[ 4 -1  4]


# Image as NumPy array

In [1]:
x = np.random.rand(4, 5)
print(x)
print("shape -", x.shape)

NameError: ignored

In [ ]:
io.imshow(x)
plt.axis("off")

In [ ]:
#height, width = x.shape[:2]
height = x.shape[0]
width = x.shape[1]
print("Height =", height)
print("Width =", width)

In [ ]:
x = np.random.rand(4, 5, 3)
height, width, nchannels = x.shape
print("Height =", height)
print("Width =", width)
print("Number of channels =", nchannels)

In [ ]:
print("Red Channel")
print(x[:, :, 0])

print("Green Channel")
print(x[:, :, 1])

print("Blue Channel")
print(x[:, :, 2])

In [ ]:
io.imshow(x)
plt.axis("off")

In [ ]:
plt.figure(figsize=(2, 2))
x_cropped = x[:3, :3, :]
io.imshow(x_cropped)
plt.axis("off")

# Real Digital Image

In [ ]:
I = io.imread("/content/images.jpg")
height, width = I.shape[:2]
print("Height =", height)
print("Width =", width)

NameError: ignored

In [ ]:
plt.figure(figsize=(4, 4))
io.imshow(I)
plt.axis("off")

In [ ]:
print(I)

In [ ]:
x = I[0, 0]
y = I[0, -1]
print(x)
print(y)

In [ ]:
print(type(x))

## Problem with **uint8**

In [ ]:
x + y

NameError: ignored

In [ ]:
# Bad way of normalization
# I = I/255

# Good way
I = img_as_float(I)
I = img_as_float(I)

NameError: ignored

In [ ]:
plt.figure(figsize=(3, 3))
io.imshow(I)
plt.axis("off")

NameError: ignored

## Example 2

In [ ]:
I = io.imread("/content/images.jpg")

NameError: ignored

In [ ]:
I.shape

NameError: ignored

In [ ]:
height, width, nchannels = I.shape
print("Height =", height)
print("Width =", width)
print("Number of channels =", nchannels)

In [ ]:
io.imshow(I)

In [ ]:
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Red channel
axes[0].imshow(I[:, :, 0], cmap="gray")
axes[0].axis("off")
axes[0].set_title("Red")

# Green channel
axes[1].imshow(I[:, :, 1], cmap="gray")
axes[1].axis("off")
axes[1].set_title("Green")

# Blue channel
axes[2].imshow(I[:, :, 2], cmap="gray")
axes[2].axis("off")
axes[2].set_title("Blue")


NameError: ignored

In [ ]:
# Only the left half of the image
I_cropped = I[:, :width//2, :]
io.imshow(I_cropped)
plt.axis("off")

In [ ]:
# Only the  bottom half of the image
I_cropped = I[height//2:, :, :]
io.imshow(I_cropped)
plt.axis("off")

In [ ]:
# flip along widht (with respect to y axis)
I_flipped = I[:, ::-1, :]
io.imshow(I_flipped)
plt.axis("off")

In [ ]:
# flip along height (with respect to x axis)
I_flipped = I[::-1, :, :]
io.imshow(I_flipped)
plt.axis("off")

In [ ]:
# Rotate 180 degree
I_rotated = I[::-1, ::-1, :]
io.imshow(I_rotated)
plt.axis("off")

# Example 3

In [ ]:
I = io.imread("bracu_logo.png")

In [ ]:
io.imshow(I)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
I.shape

In [ ]:
fig, axes = plt.subplots(1, 4, figsize=(20, 5))

# Red channel
axes[0].imshow(I[:, :, 0], cmap="gray")
axes[0].axis("off")
axes[0].set_title("Red")

# Green channel
axes[1].imshow(I[:, :, 1], cmap="gray")
axes[1].axis("off")
axes[1].set_title("Green")

# Blue channel
axes[2].imshow(I[:, :, 2], cmap="gray")
axes[2].axis("off")
axes[2].set_title("Blue")

# Alpha channel
axes[3].imshow(I[:, :, 3], cmap="gray")
axes[3].axis("off")
axes[3].set_title("Alpha")
